export const BASE_AFFIRMATIONS: string[] = [
    'I am allowed to take today at a humane pace.',
    'I can do one thing at a time.',
    'I do not have to earn rest.',
    'I am capable, even when I feel uncertain.',
    'I can meet today as it is, not as I wish it were.',
    'I am allowed to take up space.',
    'I can act with care, including toward myself.',
    'I do not need to solve everything today.',
    'I can trust myself to handle what comes next.',
    'I am doing enough for today.',
    'I can be steady without being perfect.',
    'I am allowed to change my mind.',
    'I can move gently and still make progress.',
    'I do not have to rush to be worthy.',
    'I can respond instead of react.',
    'I am learning, even when it feels slow.',
    'I can let today be ordinary.',
    'I am not behind.',
    'I can take breaks without falling apart.',
    'I can be kind without overextending myself.',
]
