export const BASE_AFFIRMATIONS: string[] = [
    'I am allowed to take today at a humane pace.',
    'I can do one thing at a time.',
    'I do not have to earn rest.',
    'I am capable, even when I feel uncertain.',
    'I can meet today as it is, not as I wish it were.',
    'I do not need to solve everything today.',
    'I can trust myself to handle what comes next.',
    'I can be steady without being perfect.',
    'I can move gently and still make progress.',
    'I am learning, even when it feels slow.',
    'I am not behind.',
    'I can take breaks without falling apart.',
    'I can start before I feel ready.',
    'A small beginning is still a beginning.',
    'I do not need the perfect window to make progress.',
    'Touching the work is enough for now.',
    'I can show up in fifteen minutes.',
    'Starting small is not the same as thinking small.',
    'I can do something, even if I cannot do everything.',
    'I do not need a full plan to take the first step.',
    'Momentum begins with the smallest move.',
    'I do not need to finish to make it count.',
    'A little effort now is not wasted.',
    'I can return to something and pick up where I left off.',
    'Starting messy is still starting.',
    'My skills are real, even when I can\'t see the whole picture yet.',
    'I\'ve solved hard problems before — I can figure this out too.',
    'What I offer has value, whether or not I\'m using it fully right now.',
    'I have more to offer than I give myself credit for.',
    'The things I do without thinking are skills someone else had to learn.',
    'I am more than my job titles and bullet points.',
    'My mind goes blank under pressure — that doesn\'t mean there\'s nothing there.',
    'I can prepare for questions without having to be perfect.',
    'The story of what I\'ve done is worth telling, even if I forget it in the moment.',
    'I\'ve handled things I didn\'t think I could handle.',
    'Not matching every requirement doesn\'t mean I can\'t do the job.',
    'I\'m allowed to take time to remember what I\'m good at.',
    'Who I am includes things that don\'t fit neatly into interview answers.',
    'I can write down my stories now, so I don\'t have to find them under pressure.',
    'My experience counts, even when I can\'t recall it on command.',
    'I don\'t have to sell myself perfectly to be worth hiring.',
    'What I\'ve accomplished is real, whether or not I can articulate it smoothly.',
]
