export const BASE_AFFIRMATIONS: string[] = [
    'I am allowed to take today at a humane pace.',
    'I can do one thing at a time.',
    'I do not have to earn rest.',
    'I am capable, even when I feel uncertain.',
    'I can meet today as it is, not as I wish it were.',
    'I do not need to solve everything today.',
    'I can trust myself to handle what comes next.',
    'I can be steady without being perfect.',
    'I can move gently and still make progress.',
    'I am learning, even when it feels slow.',
    'I am not behind.',
    'I can take breaks without falling apart.',
    'I can start before I feel ready.',
    'A small beginning is still a beginning.',
    'I do not need the perfect window to make progress.',
    'Touching the work is enough for now.',
    'I can show up in fifteen minutes.',
    'Starting small is not the same as thinking small.',
    'I can do something, even if I cannot do everything.',
    'I do not need a full plan to take the first step.',
    'Momentum begins with the smallest move.',
    'I do not need to finish to make it count.',
    'A little effort now is not wasted.',
    'I can return to something and pick up where I left off.',
    'Starting messy is still starting.',
]
